[package]
name = "aoe4_replay_launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
winreg = "0.10"
reqwest = { version = "0.12", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
dirs = "5"
flate2 = "1.0"
